[tools]
clojure = "1.12.1"
java = "temurin-21.0.6+7.0.LTS"

[tasks.format]
run = "clojure -M:format"

[tasks.test]
raw = true
run = "clojure -M:dev:test"

[tasks.antq]
raw = true
run = "clojure -M:antq"

[tasks.repl]
raw = true
run = "clojure -M:test:dev:flowstorm"
