[tools]
clojure = "1.12.1"
java = "temurin-21.0.6+7.0.LTS"

[tasks.format]
run = "clojure -M:format"

[tasks.test]
raw = true
run = "clojure -M:dev:test"

[tasks.typecheck]
raw = true
run = "clojure -M:typedclojure -e \"(require 'typed.clojure) (typed.clojure/check-dir-clj [\\\"src\\\"])\""

[tasks.antq]
raw = true
run = "clojure -M:antq"

[tasks.repl]
raw = true
run = "clojure -M:test:dev:flowstorm"

[tasks.build]
run = "clojure -T:build jar"

[tasks.clean]
run = "clojure -T:build clean"

[tasks.deploy]
run = "clojure -T:build deploy"
